# Generated by Django 2.1.11 on 2019-08-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='man',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
